POST http://0.0.0.0:8001/api/v1/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "dahsna",
    "password": "Riyadh@456"
}

###
###
GET http://0.0.0.0:8001/api/v1/auth/idp/success?id=306061815731716099&token=mWATI8ND0H_xM6IHypWswdLzFwxn3PNN4FXB7yWrHTyItw

###

GET http://0.0.0.0:8001/api/v1/auth/userdetails/305902868471218179 HTTP/1.1
Content-Type: application/json


####


GET http://0.0.0.0:8001/api/v1/auth/idp/list HTTP/1.1
Content-Type: application/json


####

POST http://0.0.0.0:8001/api/v1/auth/login/idp/305901299952517123 HTTP/1.1
Content-Type: application/json


###



